# Generated by Django 3.1.2 on 2020-10-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance', models.CharField(max_length=5)),
                ('monthly', models.CharField(max_length=5)),
                ('adress', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=20)),
                ('explain', models.TextField()),
            ],
        ),
    ]
